- id: mix-format
  name: mix format
  description: Formats Elixir files with mix format.
  language: system
  entry: mix format
  files: \.(exs|heex)?$
- id: mix-test
  name: mix test
  description: Runs Elixir tests with mix test.
  language: system
  entry: mix test
  files: \.ex$
